name: run python script from pull request

######
#
# Ensure Artifactory token is set up as a repo secret
#
######

on:
  pull_request:
    branches: ["main"] # Triggers the workflow when a pull request is created on the "main" branch

jobs:
  Ccreate-Repo:
    runs-on: ubuntu-latest # runs on VM provisionned with ubuntu image

    steps:
      - name: Checkout current repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.

      - name: Checkout script repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.
        with:
          repository: samantha-tran/test-repo
          path: ./script

      - name: Set up python version
        uses: actions/setup-python@v3
        with:
          python-version: "3.10" # Install the python version needed

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute Python script # Run the run.py to get the latest data
        run: python ./script/test.py >> log.txt

      - name: Generate summary
        run: |
          echo "### Action Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat log.txt >> $GITHUB_STEP_SUMMARY

  Merge-PR:
    needs: Create-Repo
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    steps:
      - name: Enable Automerge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
