name: test python script

on:
  pull_request:
    branches: ["main"] # Triggers the workflow when a pull request is created on the "main" branchss

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            print("This works")s
